pool:
  vmImage: 'wiindows-latest'

trigger:
  branches:
    # branch names are case senititve
    include:
    - development
    - InfoSecDevelopment
    - master
  paths:
    # triggers only on modification to contents of initiative directory
    include:
    - Initiatives/*
    exclude:
    - Inititaives/README.MD

variables:
  rootFolder: '"$(System.DefaultWorkingDirectory)/"'
  folderName: "Initiatives"
  # mgID where azure policy definitions are stored, best practice is Tentant Root Group
  managementGroupID: "389b7e7c-4be2-4213-81b1-9e3a9afabd19"
  # service connections specific to each deployment environment
  devServiceConnection: "SPN-DEV-MG-POLICY"
  cloneServiceConnection: "SPN-CLONE-MG-POLICY"
  cloneHubServiceConnection: "SPN-CLONEHUB-MG-POLICY"
  hubServiceConnection: "SPN-HUB-MG-POLICY"
  prodServiceConnection: "SPN-PROD-MG-POLICY"
  infoSecServiceConnection: "SPN-infosec-sdbx-sub-policy"
  rootMgServiceConnection: 'spn-tenant-mg-policy'

stages:
# this stage keys off the development branch
- stage: create_initiative_dev_cloud_devops
  displayName: 'Create Initiative definition in Development Subscription'
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/development'))
  jobs:
    - job:
      steps:
      - task: PowerShell@2
        displayName: 'Get Modified Initiative'
        condition: ne(variables['Build.Reason'], 'Manual')
        inputs:
          filePath: 'Libraries/Tools/Misc/checkDiff.ps1'
          arguments: '-folderName $(folderName)
                      -defRootFolder $(rootFolder)'
      - task: AzurePowerShell@5
        displayName: 'Create Initiative Definition'
        inputs:
          azureSubscription: $(devServiceConnection)
          ScriptPath: 'Libraries/Tools/Az/Create-InitiativeDef.ps1'
          ScriptArguments: '-rootFolder $(rootFolder)
                            -modifiedInitiatives $(initiatives)
                            -managementGroupName $(managementGroupID)'
          FailOnStandardError: false
          azurePowerShellVersion: LatestVersion
          pwsh: true
# this stage keys off the clone branch
- stage: create_initiative_clone_cloud_devops
  displayName: 'Create Initiative definition in clone Management Group'
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/clone'))
  jobs:
    - job:
      steps:
      - task: PowerShell@2
        displayName: 'Get Modified Initiative'
        condition: ne(variables['Build.Reason'], 'Manual')
        inputs:
          filePath: 'Libraries/Tools/Misc/checkDiff.ps1'
          arguments: '-folderName $(folderName)
                      -defRootFolder $(rootFolder)'
      - task: AzurePowerShell@5
        displayName: 'Create Initiative Definition'
        inputs:
          azureSubscription: $(cloneServiceConnection)
          ScriptPath: 'Libraries/Tools/Az/Create-InitiativeDef.ps1'
          ScriptArguments: '-rootFolder $(rootFolder)
                            -modifiedInitiatives $(initiatives)
                            -managementGroupName $(managementGroupID)'
          FailOnStandardError: false
          azurePowerShellVersion: LatestVersion
          pwsh: true
# this stage keys off the clonehub branch
- stage: create_initiative_clonehub_cloud_devops
  displayName: 'Create Initiative definition in clonehub Management Group'
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/clonehub'))
  jobs:
    - job:
      steps:
      - task: PowerShell@2
        displayName: 'Get Modified Initiative'
        condition: ne(variables['Build.Reason'], 'Manual')
        inputs:
          filePath: 'Libraries/Tools/Misc/checkDiff.ps1'
          arguments: '-folderName $(folderName)
                      -defRootFolder $(rootFolder)'
      - task: AzurePowerShell@5
        displayName: 'Create Initiative Definition'
        inputs:
          azureSubscription: $(cloneHubServiceConnection)
          ScriptPath: 'Libraries/Tools/Az/Create-InitiativeDef.ps1'
          ScriptArguments: '-rootFolder $(rootFolder)
                            -modifiedInitiatives $(initiatives)
                            -managementGroupName $(managementGroupID)'
          FailOnStandardError: false
          azurePowerShellVersion: LatestVersion
          pwsh: true

# this stage keys off the hub branch
- stage: create_initiative_hub_cloud_devops
  displayName: 'Create Initiative definition in hub Management Group'
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/hub'))
  jobs:
    - job:
      steps:
      - task: PowerShell@2
        displayName: 'Get Modified Initiative'
        condition: ne(variables['Build.Reason'], 'Manual')
        inputs:
          filePath: 'Libraries/Tools/Misc/checkDiff.ps1'
          arguments: '-folderName $(folderName)
                      -defRootFolder $(rootFolder)'
      - task: AzurePowerShell@5
        displayName: 'Create Initiative Definition'
        inputs:
          azureSubscription: $(hubServiceConnection)
          ScriptPath: 'Libraries/Tools/Az/Create-InitiativeDef.ps1'
          ScriptArguments: '-rootFolder $(rootFolder)
                            -modifiedInitiatives $(initiatives)
                            -managementGroupName $(managementGroupID)'
          FailOnStandardError: false
          azurePowerShellVersion: LatestVersion
          pwsh: true


# this stage keys off the prod branch
- stage: create_initiative_prod_cloud_devops
  displayName: 'Create Initiative definition in prod Management Group'
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/prod'))
  jobs:
    - job:
      steps:
      - task: PowerShell@2
        displayName: 'Get Modified Initiative'
        condition: ne(variables['Build.Reason'], 'Manual')
        inputs:
          filePath: 'Libraries/Tools/Misc/checkDiff.ps1'
          arguments: '-folderName $(folderName)
                      -defRootFolder $(rootFolder)'
      - task: AzurePowerShell@5
        displayName: 'Create Initiative Definition'
        inputs:
          azureSubscription: $(prodServiceConnection)
          ScriptPath: 'Libraries/Tools/Az/Create-InitiativeDef.ps1'
          ScriptArguments: '-rootFolder $(rootFolder)
                            -modifiedInitiatives $(initiatives)
                            -managementGroupName $(managementGroupID)'
          FailOnStandardError: false
          azurePowerShellVersion: LatestVersion
          pwsh: true


# this stage keys off the infosecdevelopment branch
- stage: create_initiative_def_infosec_sdbx
  displayName: 'Create Initiative definition in InfoSec Subscription'
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/InfoSecDevelopment'))
  jobs:
    - job:
      steps:
      - task: PowerShell@2
        displayName: 'Get Modified Initiative'
        condition: ne(variables['Build.Reason'], 'Manual')
        inputs:
          filePath: 'Libraries/Tools/Misc/checkDiff.ps1'
          arguments: '-folderName $(folderName)
                      -defRootFolder $(rootFolder)'
      - task: AzurePowerShell@5
        displayName: 'Create Initiative Definition'
        inputs:
          azureSubscription: $(infoSecServiceConnection)
          ScriptPath: 'Libraries/Tools/Az/Create-InitiativeDef.ps1'
          ScriptArguments: '-rootFolder $(rootFolder)
                            -modifiedInitiatives $(initiatives)
                            -managementGroupName $(managementGroupID)'
          FailOnStandardError: false
          azurePowerShellVersion: LatestVersion
          pwsh: true
# this stage keys off of master
- stage: create_initiative_def_Tenant_Root_Group
  displayName: 'Create Initiative definition in Tenant Root Group'
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/Master'))
  jobs:
    - job:
      steps:
      - task: PowerShell@2
        displayName: 'Get Modified Initiative'
        condition: ne(variables['Build.Reason'], 'Manual')
        inputs:
          filePath: 'Libraries/Tools/Misc/checkDiff.ps1'
          arguments: '-folderName $(folderName)
                      -defRootFolder $(rootFolder)'
      - task: AzurePowerShell@5
        displayName: 'Create Initiative Definition'
        inputs:
          azureSubscription: $(rootMgServiceConnection)
          ScriptPath: 'Libraries/Tools/Az/Create-InitiativeDef.ps1'
          ScriptArguments: '-rootFolder $(rootFolder)
                            -modifiedInitiatives $(initiatives)
                            -managementGroupName $(managementGroupID)'
          FailOnStandardError: false
          azurePowerShellVersion: LatestVersion
          pwsh: true